Sender: LSF System <lsfadmin@eu-g3-029>
Subject: Job 216717601: <python train.py> in cluster <euler> Exited

Job <python train.py> was submitted from host <eu-login-16> by user <jiahzhang> in cluster <euler> at Sun May  1 10:28:59 2022
Job was executed on host(s) <eu-g3-029>, in queue <gpu.4h>, as user <jiahzhang> in cluster <euler> at Sun May  1 10:29:20 2022
</cluster/home/jiahzhang> was used as the home directory.
</cluster/home/jiahzhang/PMLR10> was used as the working directory.
Started at Sun May  1 10:29:20 2022
Terminated at Sun May  1 10:30:06 2022
Results reported at Sun May  1 10:30:06 2022

Your job looked like:

------------------------------------------------------------
# LSBATCH: User input
python train.py
------------------------------------------------------------

Exited with exit code 1.

Resource usage summary:

    CPU time :                                   35.26 sec.
    Max Memory :                                 3430 MB
    Average Memory :                             2639.75 MB
    Total Requested Memory :                     5000.00 MB
    Delta Memory :                               1570.00 MB
    Max Swap :                                   -
    Max Processes :                              3
    Max Threads :                                8
    Run time :                                   74 sec.
    Turnaround time :                            67 sec.

The output (if any) follows:

Files already downloaded and verified
Files already downloaded and verified
cuda:0
---network architecture---
Sequential(
  (0): Conv2d(3, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
  (1): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
  (2): Conv2d(64, 128, kernel_size=(3, 3), stride=(2, 2), padding=(1, 1))
  (3): Conv2d(128, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
  (4): Conv2d(128, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
  (5): Conv2d(128, 256, kernel_size=(3, 3), stride=(2, 2), padding=(1, 1))
  (6): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
  (7): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
  (8): Conv2d(256, 512, kernel_size=(3, 3), stride=(2, 2), padding=(1, 1))
  (9): Conv2d(512, 512, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
  (10): Conv2d(512, 512, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
)
--------------------------
[1,   200] loss: 2.150
[1,   400] loss: 1.883
[1,   600] loss: 1.817
[1,   800] loss: 1.747
[1,  1000] loss: 1.658
[1,  1200] loss: 1.595
[1,  1400] loss: 1.548
Accuracy of the network on the 10000 test images: 46 %
Traceback (most recent call last):
  File "train.py", line 64, in <module>
    torch.save(net.state_dict(), PATH)
  File "/cluster/home/jiahzhang/.local/lib/python3.7/site-packages/torch/serialization.py", line 377, in save
    with _open_file_like(f, 'wb') as opened_file:
  File "/cluster/home/jiahzhang/.local/lib/python3.7/site-packages/torch/serialization.py", line 231, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/cluster/home/jiahzhang/.local/lib/python3.7/site-packages/torch/serialization.py", line 212, in __init__
    super(_open_file, self).__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: './log/convnet_0.pth'
